# Generated by Django 2.1.4 on 2018-12-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pict',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
