# Generated by Django 2.1.4 on 2018-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_product_pict'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter1_age',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='filter2_gender',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='filter3_type',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
